version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: hospital
    ports:
      - "3306:3306"
    volumes:
      - hospital-db:/var/lib/mysql

volumes:
  hospital-db: